spring
  application
    name:sweater
  jpa
    hibernate
      ddl-auto:create
    database:postgresql
    show-sql:false
  datasource
    url:jdbc:postgresql://localhost:5432/sweater
    username:sweater
    password:sweater
    driver-class-name:org.postgresql.Driver

